### ISSUE TITLE
floppy/zz-start-sshd.cmd is referenced, but the file is missing

### ISSUE THREAD

**Issue by ajschroeder** [boxcutter/windows#109]
I tried building the 'eval-win10x64-enterprise' image and the JSON file is referencing a windows command file called 'zz-start-sshd.cmd' in the floppy directory. This results in the make stopping because it can't find the file. As far as I can tell has been replaced by 'zz-start-transports.cmd'. I am trying the build now and it is now downloading the Win10 ISO.

I referenced the 'eval-win7x64-enterprise.json' file to clue me in about the missing command script.

**Comment by rasa** [comment]
See #108

**Comment by tas50** [comment]
Fixed on master. I missed the Windows 10 boxes in my find/replace somehow.
