### ISSUE TITLE
Windows 10 builds don't install all Windows Updates

### ISSUE THREAD

**Issue by claudehenchoz** [boxcutter/windows#12]
It seems that when running Windows 10 builds, only some updates are installed.

In a deployed box, after enabling UAC again, it seems that the "Windows Update" applet downloads more updates (and doesn't even start if UAC is disabled).

Could the installation of those updates somehow be fixed?

**Comment by arizvisa** [comment]
This doesn't seem to happen \_exactly\_ for me, are you still interested in someone looking into this, or has this gotten completely stale?

**Comment by arizvisa** [comment]
This issue has had no discussion or input for 5 months. I've tagged it as stale and as a result this issue will be closed in 1 month.

If you disagree and feel this decision is a mistake, please let me know and I'll remove the label.

**Comment by arizvisa** [comment]
Closing this issue due to being stale.
