### ISSUE TITLE
README doesn't say what `update` true|false does

### ISSUE THREAD

**Issue by dougireton** [boxcutter/windows#13]
I see this output when I build a box, but I don't know what setting the `update=false` vs. `update=true` Makefile variable does.

```batch
packer build -only=virtualbox-iso -var 'cm=nocm' 
-var 'version=1.0.4' -var 'update=false' -var 'headless=false'
```

I searched this repo for `update` but I couldn't figure it out. Help!

**Comment by rasa** [comment]
Apparently nothing, at the moment. See
https://github.com/boxcutter/windows/commit/96aedfac45c7d227066e4ef6922ebaab28b19051
