### ISSUE TITLE
Windows 8.1 WinRM never setup

### ISSUE THREAD

**Issue by tas50** [boxcutter/windows#138]
WinRM setup never happens on Windows 8.1. It has to be manually kicked off before packer can connect.

**Comment by conradjones** [comment]
it looks like the script disables the service

**Comment by dragon788** [comment]
This might a similar fix to one that was submitted recently to chef/bento for Windows 10, I'll take a peek and see if this is still an issue, as I suddenly found myself with a need to build Windows 8.1 again.

**Comment by arizvisa** [comment]
This issue and template/eval-win2008r2-standard-no-cm-0.1.0.box still asking you to choose the wim image is actually first on my todo. So if someone gets to this one first, lmk and I'll merge it.

**Comment by arizvisa** [comment]
I was just able to build `eval-win81x86-enterprise` and `eval-win81x64-enterprise` while testing out PRs #239 and #240. Do you recall if this was happening in the regular `win81x*-*.json` templates? If not, this issue might've been indirectly fixed...

**Comment by arizvisa** [comment]
This has been closed by PR #243. If it isn't please let me know and I'll re-open.
