### ISSUE TITLE
broken download link for wget

### ISSUE THREAD

**Issue by patrickhuber** [boxcutter/windows#148]
In the file: https://github.com/boxcutter/windows/blob/master/floppy/01-install-wget.cmd

wget's current version is no longer available from https://eternallybored.org/misc/wget/current/wget.exe. The link returns a 404.

Using the version specific urls works: https://eternallybored.org/misc/wget/1.19.4/64/wget.exe

**Comment by taitho** [comment]
Very good, thanks

**Comment by arizvisa** [comment]
I think at some point we should use the file provisioner to drop files like this directly into the template.

Nonetheless, can the OP close this issue due to resolution?
