### ISSUE TITLE
Windows 10x64 Templates Fail to Boot with Windows 1709 on High Sierra

### ISSUE THREAD

**Issue by john-terrell** [boxcutter/windows#149]
Both the VirtualBox and VMWare sections will fail to load the downloaded ISO (they hang at the blue Windows logo.)   To make this work, I had to specify specific hypervisor options for each hypervisor:

For VMWare I had to specify:
"version": "12",

For VirtualBox:
"vboxmanage": [
        ...
        [
          "modifyvm",
          "{{.Name}}",
          "--paravirtprovider",
          "kvm"
        ]
      ]

I don't have a Parallels Hypervisor to test.

The default options for either didn't work for Windows 10 1709.

**Comment by taitho** [comment]
Please, i testing...

**Comment by arizvisa** [comment]
I'm testing this right now. It seems that the windows 10 installers have some other issue as well that I might as well track down too. Fortunately if it's simply a `hw_version` issue for the `vmware-iso` builder, then we can simply bump the default value to 12.

**Comment by arizvisa** [comment]
Did PR #247 affect this at all for you? (It's been merged already, so you just need to retry)

**Comment by arizvisa** [comment]
Due to the lack of response on this issue, I've tagged it as stale and thus it will be closed in a month. If you feel this is in error, let me know and I'll untag.

**Comment by arizvisa** [comment]
Closing this issue as it has gone stale due to a lack of interaction that has extended to almost a year. If you feel this is in error, please let me know and I will re-open.
