### ISSUE TITLE
WIndows 10 VMWare Hardware Version issues

### ISSUE THREAD

**Issue by stootles** [boxcutter/windows#153]
So I have been attempting to build a win10x64 eval box on OSX 10.13.4 with Fusion 10.1.1. Packer version 1.2.3

Windows 10 would boot and show the windows logo but the spinning balls would never appear. I left it in this state for several hours quite a few times. Bastardising the boxcutter tools trying to identify what was not working.

I eventually boot straight off the ISO directly and inspected the settings Fusion gave, which was hardware version 14. Checking packer, the default (and only supported) is version 9. When I attempted to change to version 9 in my newly created VM, Fusion informed me that version 9 is incompatible with my guest OS and would not let me change it.

Added a version line to the eval-win10....json file seems to have solved this for me. Well I am at least past the boot logo and well into the installation. I cant be the only person who has been or will be bitten by this issue. So hopefully this might help someone else.

Cheers,

S.

```
diff --git a/eval-win10x64-enterprise.json b/eval-win10x64-enterprise.json
index c0dc10c..4f20070 100644
--- a/eval-win10x64-enterprise.json
+++ b/eval-win10x64-enterprise.json
@@ -29,6 +29,7 @@
       "tools_upload_flavor": "windows",
       "type": "vmware-iso",
       "vm_name": "eval-win10x64-enterprise",
+      "version": "10",
       "vmx_data": {
         "cpuid.coresPerSocket": "1",
         "memsize": "{{ user `memory` }}",
```

**Comment by GeoffWilliams** [comment]
this helped me! I'm using VMWare workstation 14 and then 15... Had to add `"version": "14"` to get it working, then figured change to `15` on upgrade - thanks, you saved me a headache

**Comment by arizvisa** [comment]
@stootles, pezhore's PR #153 exposes an option that exposes the setting of the vmware hw version via a user variable, and the Makefile. Does that help resolve this issue?

**Comment by stootles** [comment]
Absolutely. Reviewing his change and it looks like it ticks all the boxes with a very nice solution. Nice work @pezhore
