### ISSUE TITLE
Microsoft .iso URL returns 502

### ISSUE THREAD

**Issue by tobinquadros** [boxcutter/windows#157]
My team is getting a `502` response when attempting to build the Windows 10 Enterprise 64 bit image from this URL: https://github.com/boxcutter/windows/blob/e7eef54f8dc6318bd1cc1a57562cad0a548e5434/eval-win10x64-enterprise.json#L183

The problem occurs on and off of our company network, and for teams in Melbourne, AU and Phoenix, AZ. The issue can be replicated with a `curl` request:

```
curl -IXGET http://care.dlservice.microsoft.com/dl/download/6/5/D/65D18931-F626-4A35-AD5B-F5DA41FE6B76/16299.15.170928-1534.rs3_release_CLIENTENTERPRISEEVAL_OEMRET_x64FRE_en-us.iso
```

Have the care.dlservice.microsoft.com servers been deprecated or the .iso path changed? Is there a new substitute URL we can use, something like https://www.microsoft.com/en-us/evalcenter/evaluate-windows-10-enterprise ?

**Comment by tobinquadros** [comment]
Fascinating, `wget` succeeds for me too. It appears Packer is using Golang's `net/http` package: https://github.com/hashicorp/packer/blob/dcb870bcbf856bbc9eb68b864415049c27d994b5/common/download.go. I wonder if `curl` and the Packer implementation have some common issue occurring with this specific request? Maybe this should be directed to an issue in packer?

**Comment by StefanScherer** [comment]
I‘ve updated the links in https://github.com/StefanScherer/packer-windows/pull/100/files and https://github.com/StefanScherer/packer-windows/pull/113/files

**Comment by tobinquadros** [comment]
Awesome, those links are working for us. Thanks!

**Comment by nickgarber** [comment]
Hi @tobinquadros, I believe that with PR#158 merged this issue can now be marked closed. How's it look to you?

**Comment by tobinquadros** [comment]
👍
