### ISSUE TITLE
Error detecting host IP: Could not find vmnetdhcp conf file on VMWare Workstation 15 linux

### ISSUE THREAD

**Issue by GeoffWilliams** [boxcutter/windows#160]
I've been getting error:

```
2018/10/27 11:35:23 packer: 2018/10/27 11:35:23 Connected to VNC desktop: eval-win10x64-enterprise
2018/10/27 11:35:23 packer: 2018/10/27 11:35:23 Error finding VMWare DHCP Server Configuration (dhcp.conf) under device path: /etc/vmware/nat
2018/10/27 11:35:23 ui error: ==> vmware-iso: Error detecting host IP: Could not find vmnetdhcp conf file:
==> vmware-iso: Error detecting host IP: Could not find vmnetdhcp conf file:
```

Full error: https://gist.github.com/GeoffWilliams/26a80f73fb0b305659b95592b5f68e27

Immediately after starting build of `eval-win10x64-enterprise.json` on Ubuntu 18.04 running VMWare Workstation 15, packer 1.3.1. The issue seems to be related to https://github.com/hashicorp/packer/issues/6745 but the suggested fixes (downgrade to packer 1.2.2/add `"network": "nat"`) didn't work for me.

I found another fix though: you seem to have to use the actual network name and specify it in `eval-win10x64-enterprise.json` (eg to build windows 10), right after `winrm_username` around line 43:

```
"network" : "vmnet8"
```

Hope that helps someone

**Comment by chrisarm** [comment]
Arch with VMWare Workstation 14, packer 1.3.5.

I was getting the same error and tried "vmnet8" for the "network" value in the json, but it only worked once I set the VMWare Workstation netmap.conf file to the same network0.device = "vmnet8" as well:


> sudoedit /etc/vmware/netmap.conf

`
network0.name = "nat"

network0.device = "vmnet8"
`

@GeoffWilliams : Cheers for the pointer!

**Comment by arizvisa** [comment]
Does it make sense to expose this to users in boxcutter-windows? The specific option only affects VMware specifically, and it's a packer-specific issue with packer being unable to determine the network mapping to use.

That network option is actually intended to build templates in "hostonly" mode which we currently don't support as our provisioning scripts contact the internet directly.

**Comment by arizvisa** [comment]
Due to lack of response, I'm marking this issue as stale. In one month this issue will be closed as "wontfix" unless someone objects. Lmk if you think this is a mistake and if we should proceed in some particular direction and I will leave it open. Thanks!

**Comment by arizvisa** [comment]
Closing this. Let me know if closing it is a mistake and I'll re-open it. Thanks.
