### ISSUE TITLE
Several downloads via http without TLS (https), security issue

### ISSUE THREAD

**Issue by dragetd** [boxcutter/windows#172]
Some links in documents and several scripts download resources via HTTP without TLS. For the Microsoft Schema definitions this is irrelevant. Also the ISO download links (which and invalid anyways) there is a checksum check.

But on other occations there are just HTTP links where software is downloaded, which is a security problem.

Even the README.md links to http://www.smartystreets.com instead of https://smartystreets.com.

If nobody objects, I will go through all HTTP:// links and check if they can be updated to https and create a PR. :)

**Comment by arizvisa** [comment]
Do you mind if I close this and mark it as a duplicate of #177?

**Comment by dragetd** [comment]
Yes, let is discuss there! :-)

**Comment by arizvisa** [comment]
Marked as a duplicate of #177.
