### ISSUE TITLE
add Ansible as config management tool

### ISSUE THREAD

**Issue by bbaassssiiee** [boxcutter/windows#20]
pupper & chef are present, however I'd like to use Ansible.

**Comment by annawake** [comment]
What extra needs to be installed to provision an image with Ansible?  As far as I know, the image has everything needed as it installs the necessary Ansible agents - ssh and WinRM.  What else is necessary?

**Comment by bbaassssiiee** [comment]
add chocolatey for packages.

**Comment by juju4** [comment]
Missing winrm configuration: tested on win2012r2.
https://github.com/ansible/ansible/blob/devel/examples/scripts/ConfigureRemotingForAnsible.ps1
cant win_ping/setup before execution else.
After, it's ok

As for chocolatey, should be easy as calling win_chocolatey. module will install it if missing
http://docs.ansible.com/ansible/win_chocolatey_module.html

Thanks
