### ISSUE TITLE
Get rid of Cygwin and SSH scripts

### ISSUE THREAD

**Issue by rasa** [boxcutter/windows#26]
Once WinRM is fully tested, let's get rid of the Cygwin and SSH scripts (or an least move them to an `unmaintained` folder.

**Comment by rylarson** [comment]
We will still need Cygwin for rsync though.

**Comment by tas50** [comment]
I'd love to kill off the SSH scripts. WinRM seems to work flawlessly in my testing and we've been using images with only WinRM within Chef for years. Having 3 scripts for each build is super maintenance heavy.

**Comment by TwoSlick** [comment]
WinRM may perform fine for transferring a few small files, but in my experience, it had very poor transfer speeds, and large files would often timeout.
