### ISSUE TITLE
Provisioning halts on "Waiting for WinRM to become available..."

### ISSUE THREAD

**Issue by metmajer** [boxcutter/windows#31]
Hi - thank you for this awesome compilation of Packer templates!

When building a Vagrant box via `make virtualbox/eval-win2008r2-standard` the process keeps waiting at the following step even after the Windows installation has already finished:

```
==> virtualbox-iso: Creating floppy disk...
==> virtualbox-iso: Creating virtual machine...
==> virtualbox-iso: Creating hard drive...
==> virtualbox-iso: Attaching floppy disk...
==> virtualbox-iso: Creating forwarded port mapping for SSH (host port 3971)
==> virtualbox-iso: Executing custom VBoxManage commands...
==> virtualbox-iso: Starting the virtual machine...
==> virtualbox-iso: Waiting 10s for boot...
==> virtualbox-iso: Typing the boot command...
==> virtualbox-iso: Waiting for WinRM to become available...
```

I have validated that WinRM is running inside the Windows guest. This does not happen when I create a virtual machine for VMware (which is not an option for me in the long run). Any clues how VirtualBox could play into this? Thanks!

### Environment

- Mac OS X 10.10.4 (Yosemite)
- Vagrant 1.7.4
- VirtualBox 4.3.28r100309
- Packer 0.8.2

#### Vagrant Plugins

- vagrant-share (1.1.4, system)
- vagrant-winrm (0.7.0)

**Comment by jboeshart** [comment]
Try updating Packer to 0.8.3. I _think_ it's fixed in there based on [1] but I've not been able to validate for myself. 

[1] https://github.com/mitchellh/packer/pull/2505

**Comment by metmajer** [comment]
Seems like this release is still not available by now, but I'll keep watching. Will keep you posted if that fixed it for me. Thanks @jboeshart!

**Comment by jboeshart** [comment]
Yup, see that now too, I thought it had already been released. In the meantime to get around it you can adjust the port mappings on the VirtualBox image once it's been created. If you map 5985 to 5985 it will continue with the build.

**Comment by metmajer** [comment]
Packer 0.8.3 has been released over the weekend. That fixed the issue. Many thanks @jboeshart for the pointer!
