### ISSUE TITLE
Chef installation doesn't work if an x.y.z version is specified

### ISSUE THREAD

**Issue by 4min** [boxcutter/windows#32]
Chef 11.18.10+ installation doesn't work if version is specified. Apparently Chef has changed URLs for MSIs to this format:
https://opscode-omnibus-packages.s3.amazonaws.com/windows/2008r2/x86_64/chef-client-11.18.10-1.msi
That happened during the release of 11.18.10

This can't be fixed by passing a custom URL variable via Makefile.local either, because only "CM" and "CM_VERSION" get passed through to the VM.

Overall, for all versions: CM_VERSION syntax does not match the one described in readme:
- The value of CM_VERSION should have the form x.y or x.y.z, such as CM_VERSION := 11.12.4

In fact the only value that would work right now would be "11.12.4-1". We can safely add "-1" to simplify interface, for all the released versions of Chef-client with the following exceptions:
- https://opscode-omnibus-packages.s3.amazonaws.com/windows/2008r2/x86_64/chef-windows-11.12.8-2.windows.msi
- https://opscode-omnibus-packages.s3.amazonaws.com/windows/2008r2/x86_64/chef-client-11.4.4-2.windows.msi

**Comment by 4min** [comment]
Submitted a pull request with fix ^^

**Comment by annawake** [comment]
Rather than hardcoding the versions, try getting a result from the omnitruck API: https://docs.chef.io/api_omnitruck.html
