### ISSUE TITLE
Unable to unzip "C:\Users\vagrant\windows.iso"

### ISSUE THREAD

**Issue by carlskii** [boxcutter/windows#37]
I'm getting a build error (VmWare) with what looks like the vmtool.bat file. If I remove it from the Packer config file it works. VirtualBox and Parallels is working OK.

```
==> vmware-iso: Provisioning with shell script: script/vmtool.bat
    vmware-iso: ==> Creating "C:\Users\vagrant\AppData\Local\Temp\sevenzip"
    vmware-iso: ==> Downloading "http://www.7-zip.org/a/7z938-x64.msi" to "C:\Users\vagrant\AppData\Local\Temp\sevenzip\7z938-x64.msi"
    vmware-iso: ==> Installing "C:\Users\vagrant\AppData\Local\Temp\sevenzip\7z938-x64.msi"
    vmware-iso: 2015-10-01 11:16:36 URL:http://d.7-zip.org/a/7z938-x64.msi [1513472/1513472] -> "C:/Users/vagrant/AppData/Local/Temp/sevenzip/7z938-x64.msi" [1]
    vmware-iso: ==> Copying "C:\Program Files\7-Zip\7z.exe" to "C:\Windows"
    vmware-iso: 1 file(s) copied.
    vmware-iso: 1 file(s) copied.
    vmware-iso: ==> Extracting the VMWare Tools installer
    vmware-iso:
    vmware-iso: 7-Zip [64] 9.38 beta  Copyright (c) 1999-2014 Igor Pavlov  2015-01-03
    vmware-iso:
    vmware-iso: Processing archive: C:\Users\vagrant\windows.iso
    vmware-iso:
    vmware-iso: Error: Can not open file as archive
    vmware-iso:
    vmware-iso: Can't open as archive: 1
    vmware-iso: Files: 0
    vmware-iso: Size:       0
    vmware-iso: Compressed: 0
    vmware-iso:
    vmware-iso: Kernel  Time =     0.000 =    0%
    vmware-iso: User    Time =     0.000 =    0%
    vmware-iso: Process Time =     0.000 =    0%    Virtual  Memory =      1 MB
    vmware-iso: Global  Time =     0.000 =    0%    Physical Memory =      3 MB
    vmware-iso: ==> WARNING: Error 2 was returned by: 7z e -o"C:\Users\vagrant\AppData\Local\Temp\vmware" "C:\Users\vagrant\windows.iso" "setup64.exe"
    vmware-iso: ==> Unable to unzip "C:\Users\vagrant\windows.iso"
    vmware-iso:
    vmware-iso: Pinging 127.0.0.1 with 32 bytes of data:
    vmware-iso: Reply from 127.0.0.1: bytes=32 time<1ms TTL=128
    vmware-iso: Reply from 127.0.0.1: bytes=32 time<1ms TTL=128
    vmware-iso: Reply from 127.0.0.1: bytes=32 time<1ms TTL=128
    vmware-iso: Reply from 127.0.0.1: bytes=32 time<1ms TTL=128
    vmware-iso:
    vmware-iso: Ping statistics for 127.0.0.1:
    vmware-iso: Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
    vmware-iso: Approximate round trip times in milli-seconds:
    vmware-iso: Minimum = 0ms, Maximum = 0ms, Average = 0ms
    vmware-iso: ==> Script exiting with errorlevel 1
==> vmware-iso: Stopping virtual machine...
==> vmware-iso: Deleting output directory...
Build 'vmware-iso' errored: Script exited with non-zero exit status: 1

==> Some builds didn't complete successfully and had errors:
--> vmware-iso: Script exited with non-zero exit status: 1

==> Builds finished but no artifacts were created.
make: *** [box/vmware/win2012r2-datacenter-nocm-1.0.4.box] Error 1
```

**Comment by vFondevilla** [comment]
Same here with VMware Fusion 8 Pro, Packer 0.8.6 and Vagrant 1.7.4

**Comment by vmenajr** [comment]
I'm having the same issue and currently running with the suggestion from the packer thread... However, I also decided to add floppy/update.bat to win7x64-enterprise.json.  I mistakenly assumed that simply setting "updates=true" on the packer build -var line would run the updates.

**Comment by icnocop** [comment]
Can you explicitly set `"tools_upload_path": "C:/Users/vagrant/windows.iso"` or `"tools_upload_path": "c:/Windows/Temp/windows.iso"`?

**Comment by jstortz** [comment]
Same here with VMware Fusion 8.02 Pro, Packer 0.8.6 and Vagrant 1.7.4

**Comment by icnocop** [comment]
If you are using WinRM, see https://github.com/packer-community/packer-windows-plugins/issues/25

**Comment by icnocop** [comment]
Not sure if this will help, but as suggested [here](https://github.com/packer-community/packer-windows-plugins/issues/53#issuecomment-102647139) and [here](https://github.com/packer-community/packer-windows-plugins/issues/53#issuecomment-108727662) you can try:
setting WINRMCP_DEBUG=1 (for logging purposes)
setting MaxConcurrentOperationsPerUser to 1000
setting MaxMemoryPerShellMB to 1000

**Comment by smudgerdan** [comment]
To get around this issue I disabled "guest_additions_mode" and instead read in the .vbox_version file and use it to create a URL in order to download the iso from [download.virtualbox.org/virtualbox](http://download.virtualbox.org/virtualbox/).  There is still the chance that the .vbox_version file causes the error but as it is much smaller file I have only seen it fail once.

**Comment by arizvisa** [comment]
I don't seem to have this issue, but despite that is this issue still occuring? A lot of things have changed since then so I just want to be sure.

I've marked this issue as stale as this is almost 4 years old. Iff nobody has any objections, I'll close it in one month.

**Comment by arizvisa** [comment]
Closing this. Let me know if closing it is a mistake and I'll re-open it. Thanks.
