### ISSUE TITLE
Possibly incorrect output filename for 'standard' boxes.

### ISSUE THREAD

**Issue by jrmash** [boxcutter/windows#40]
I am currently working with the 'eval-win2012r2-standard' box and noticed a couple oddities with it when the virtual machine files are written out:
- This box appears to be using the 'vagrantfile-eval-win2012r2-standard-ssh.tpl' file when finalizing Vagrantfile creation.
- This box also appears to be written out as 'eval-win2012r2-standard-ssh-nocm-1.0.4.box', even though the standard shouldn't be using SSH.

I think this issue is related to issue #27 and may affect some/most of the "standard" box json files.

**Comment by arizvisa** [comment]
This issue seems to have been fixed already and smells pretty stale with it being 4 years old, can I close and mark as a duplicate?

**Comment by jrmash** [comment]
That's reasonable, thanks for circling back on this.

**Comment by arizvisa** [comment]
Closed as a duplicate of #27.
