### ISSUE TITLE
Guide for enabling updates?

### ISSUE THREAD

**Issue by bdejong** [boxcutter/windows#46]
I'm kind of missing a guide on how to enable automatic updates on box-creation-time. I see there's an update.bat script, but this seems to be used in only a few of the packer templates.

Would this just be a matter of updating all the templates and adding update.bat in there?

**Comment by vmenajr** [comment]
I added update.bat as follows in an attempt to make it work

```json
  "provisioners": [
    {
      "environment_vars": [
        "CM={{user `cm`}}",
        "CM_VERSION={{user `cm_version`}}",
        "UPDATE={{user `update`}}"
      ],
      "scripts": [
        "script/vagrant.bat",
        "script/cmtool.bat",
        "script/vmtool.bat",
        "floppy/update.bat"
      ],
      "type": "windows-shell"
    },
    {
      "type": "windows-restart"
    },
    {
      "environment_vars": [
        "CM={{user `cm`}}",
        "CM_VERSION={{user `cm_version`}}",
        "UPDATE={{user `update`}}"
      ],
      "scripts": [
        "script/clean.bat",
        "script/ultradefrag.bat",
        "script/uninstall-7zip.bat",
        "script/sdelete.bat"
      ],
      "type": "windows-shell"
    }
  ],
```

After about an hour of "Searching for updates..." I received the following
**c:\Windows\Temp\script.bat?.wsf(83, 18) Microsoft VBScript runtime error: Permission denied**

**Comment by vmenajr** [comment]
Looks it failed to accept the EULA

***vmware-iso: 236> note: Windows Malicious Software Removal Tool x64 - November 2015 (KB890830) has a license agreement that must be accepted:***

**Comment by arizvisa** [comment]
Is this issue stale? Do either of you care about this anymore? Heh.

**Comment by arizvisa** [comment]
Due to the lack of response on this issue, I'm tagging this as stale. If you feel this is in error, you haven't moved past this, or would still like this to be worked on. Let me know and I'll untag it. This issue will be closed in 1 month-ish.

**Comment by arizvisa** [comment]
Closing this issue as it's been stale for over a month.
