### ISSUE TITLE
VM tools: Attach vs upload?

### ISSUE THREAD

**Issue by dusek** [boxcutter/windows#53]
Hi,

I was just wondering why are the VM Tools uploaded (i.e. `guest_additions_mode` is unspecified, leading to upload), and not attached. I find it much more convenient to us the value of `attach`, because it is instant (especially when compared to WinRM - it takes me ~4 minutes for VirtualBox vs. CD attach which takes 1-2 seconds, see also packer-community/winrmcp#6), and with WinRM upload can fail due to insufficient value of WinRM memory setting (see also packer-community/winrmcp#10).

I am considering submitting a PR for having `"guest_additions_mode": "attach"` (and same for parallels and vmware), just wanted to make sure there is not a reason it is done the current way before I prepare it and submit it.

**Comment by modille** [comment]
+1

I'm also curious.

I was getting errors with `upload` on VirtualBox, but using `attach` instead worked fine.

**Comment by dragon788** [comment]
Does attach correctly remove the virtual CD device once the build has completed? There was a bug at one point in that Packer didn't always remove this and it confused some platforms when they encountered the drive upon box import.

**Comment by legal90** [comment]
I guess, this issue could be closed because #73 is merged.

**Comment by arizvisa** [comment]
As per @legal90s suggestion, I'm closing this as it was resolved by PR #73.

If either of you have any objections, lmk and I'll re-open.
