### ISSUE TITLE
Meaning of "cygwin" and "ssh" suffixes on json box files? 

### ISSUE THREAD

**Issue by donbecker** [boxcutter/windows#55]
Sorry if this is described already elsewhere, but what is the differences between these? 

For example, I've diff'ed "win2012r2-standard.json", "win2012r2-standard-ssh.json" and "win2012r2-standard-cygwin.json" and see some differences between ssh and winrm, but the precise differences and when to use them isn't readily apparent to me.

I'm building boxes on Windows 7 using Cygwin...should I be using the "-cygwin" post fixed files?

**Comment by patrick-hill** [comment]
@donbecker If you haven't already discoverd by now, the suffixes identify what "communication" software is install on the box during creation.
For example, building a -cygwin box will have cygwin installed on that box and openssh on the -ssh's

Does that make sense?

**Comment by donbecker** [comment]
@patrick-hill Yep, that makes sense thanks!
