### ISSUE TITLE
is it possible to create an image for Openstack

### ISSUE THREAD

**Issue by blacktop** [boxcutter/windows#77]
A kvm qcow2 ?

If not with your repo can you point me in the right direction?

Much thanks

**Comment by m03** [comment]
@blacktop, you can use an inline/script in a post-processor to run qemu-img to convert the vmdk to a qcow2.

You'd need to start with an ISO that has the virtio drivers slipstreamed (or otherwise get them into the image), but it's doable.

**Comment by lfarnell** [comment]
@blacktop If I sent a PR to add QEMU support for Windows would that be a benefit you think? I personally wouldn't want to run qemu-img to convert it from another virtual hard disk format

**Comment by blacktop** [comment]
@lfarnell yes that would be awesome!!

**Comment by blacktop** [comment]
does it already support kvm?
