### ISSUE TITLE
x64 puppet version selection doesn't work

### ISSUE THREAD

**Issue by balous** [boxcutter/windows#78]
Look at the puppet installer file naming at the download server (https://downloads.puppetlabs.com/windows):

```
puppet-3.8.7-x64.msi
puppet-x64-latest.msi
```

So cmtool's simple pattern:

```
PUPPET_URL=https://downloads.puppetlabs.com/windows/puppet-x64-%CM_VERSION%.msi
```

can't address both variants - CM_VERSION=latest and CM_VERSION=3.8.7. Actually, just the 'latest' works.

**Comment by tas50** [comment]
You should get the correct Puppet URL on master now. Give it a try and feel free to open this back up if you're still having issues
