### ISSUE TITLE
7-zip is not uninstalled correctly.

### ISSUE THREAD

**Issue by GolubevV** [boxcutter/windows#80]
Currently, the 7-zip is getting installed as part of Windows boxes provisioning logic, by the script named **vmtool.bat**.

It is supposed to be completely and correctly removed at a later stage by the dedicated script **uninstall-7zip.bat**, however it does not perform the correct uninstall of the 7-zip from the registry (and it is still present in the "Programs and Features"  in Control panel). 
This result in some unpredictable and hard to track behavior, when 7-zip is getting installed on the created box as part of integration tests, for example, for Chef cookbooks. 

Here is the corresponding message from the packer\boxcutter log:

> ```
> virtualbox-iso: ==> Uninstalling 7zip
> virtualbox-iso: ==> WARNING: Directory not found: "C:\Users\vagrant\AppData\Local\Temp\sevenzip"
> ```

It happens due to the fact, that the following piece of code does not get executed:
`msiexec /qb /x "%SEVENZIP_PATH%"`
as the msi file and its parent folder are getting cleaned up by previous script, named **clean.bat**, which performs complete remove of all folders from the %TEMP% folder, including the download folder of 7-zip.

The possible solution can be to exclude the **sevenzip** folder from the cleanup, so that it can be correctly uninstalled.

**Comment by tas50** [comment]
I've like to move away from using 7zip altogether. We can unzip the files directly via Powershell, which would avoid the whole mess of installing / uninstalling 7zip multiple times. Look for that fix in the future one I get a nice powershell based pattern

**Comment by tas50** [comment]
I've built several hosts today and all of them correctly removed 7zip so I'm going to close this issue at now. If you're still having issues with the latest code in master feel free to open it back up
