### ISSUE TITLE
README `make ssh-*` example doesn't work

### ISSUE THREAD

**Issue by Thiel** [boxcutter/windows#81]
Hi,

I'm new to packer but is still familiar with Makefiles.
So I followed blindly the Readme in order to build myself a windows box, however the command `make ssh-box/virtualbox/win2008r2-standard-nocm.box` provided in the Makefile doesn't work.

The reason is since https://github.com/boxcutter/windows/commit/1197bb0f80e62f7544d21e2257ccbcc7b549bb99#diff-b67911656ef5d18c4ae36cb6741b7965R50 version has been added to the generated box file name. But it wasn't updated on the Makefile.
The `BOX_VERSION` variable is read from the `/VERSION` file which is currently (on commit 3f4c84a17337af5217e96c08bac7c895c2aae3e7) at 1.0.4

Thus `make ssh-box/virtualbox/win2008r2-standard-nocm.box` doesn't work anymore but `make ssh-box/virtualbox/eval-win2008r2-standard-nocm-1.0.4.box` do work.

Shall we update  `make ssh-box/virtualbox/win2008r2-standard-nocm.box` to  `make ssh-box/virtualbox/win2008r2-standard-nocm-$(cat VERSION).box` ?

Best,

**Comment by arizvisa** [comment]
Does this issue still seem to happen? The versioning and naming seems to have changed vastly since this question was first asked.

No worries if you've already moved past this issue and don't care to resolve it anymore. If there's no response in the next while, I'll tag this issue as "stale", and close it in a month if that's the case.

**Comment by arizvisa** [comment]
Due to the lack of response on this issue, I've tagged it as stale and thus it will be closed in a month. If you feel this is in error, let me know and I'll untag.

**Comment by arizvisa** [comment]
Closing this issue as it has gone stale due to a lack of interaction. This is suspected to have been fixed, as the configuration manager naming schemes have changed since the issue was first reported. If you feel the closing of this is in error, please let me know and I will re-open.
