### ISSUE TITLE
sdelete 2.0 incompatible

### ISSUE THREAD

**Issue by krissi** [boxcutter/windows#84]
It seems SDelete v2.0 which was released on July 4, 2016 is incompatible with the build process. The URL `http://live.sysinternals.com/sdelete.exe` which is used in `script/sdelete.bat`, was updated to the new version.

The build process executes `sdelete.exe` but does not continue after the process exited. I waited for the continuation for 3 days before I cancelled packer. After replacing the `SDELETE_URL` to a self-hosted SDelete v1.6.1 the build finished successfully.

I had this issue with `make vmware/eval-win2008r2-standard` on Debian jessie 8.6 with packer 0.10.1 and VMware Workstation Pro 12.5.0 on Kernel 3.16.0-4-amd64.

It would be great if users having this issue report their configuration as well

**Comment by smudgerdan** [comment]
Here is the forum post about the v2.0 hanging issue http://forum.sysinternals.com/sdelete-hangs-at-100_topic32267.html?KW=sdelete

**Comment by tas50** [comment]
I'm working on pulling the old sdelete from archive.org and unzipping it using Powershell. Expect that soon, which will get us back to the previous speed / reliability

**Comment by rasa** [comment]
Seems http://web.archive.org/web/20160404120859/http://live.sysinternals.com/sdelete.exe is version 1.6.1, and http://web.archive.org/web/20160722080117/http://live.sysinternals.com/sdelete.exe is 2.0.0

**Comment by tas50** [comment]
That link was exactly what I needed. I just merged that into master in https://github.com/boxcutter/windows/pull/112

**Comment by philippe-granet** [comment]
Url have changed : http://web.archive.org/web/20160404120859if_/http://live.sysinternals.com/sdelete.exe
