### ISSUE TITLE
Is this repo still being maintained?

### ISSUE THREAD

**Issue by lfarnell** [boxcutter/windows#88]
It looks as though not much activity is happening in the repo. Is it still being actively maintained? I wouldn't mind helping maintain the repo if people still see the value.

**Comment by JoelBCarter** [comment]
Same here.  It's been highly valuable and I'd love to give back.

**Comment by tas50** [comment]
There's certainly value in helping and testing to improve the overall setup would be greatly appreciated. I just merged a pile of PRs I've been putting together while working on creating updated Windows box internally at Chef. I think that gets thing into a better state, but there's some large scale refactoring that would really help ease the maintenance of things.
