### ISSUE TITLE
Hyper-V Builder Support

### ISSUE THREAD

**Issue by JoelBCarter** [boxcutter/windows#89]
This repo is not that far from supporting Hyper-V ([hyperv-iso](https://www.packer.io/docs/builders/hyperv-iso.html)) as a builder.  Some OS versions might just be as simple as a copy/paste from another builder with a `packer validate` to remove any unsupported JSON properties.  It seems like it would be pretty helpful for a lot of folks to use vanilla-Windows (no Cygwin required) to build Windows Images.

**Comment by mwinfie** [comment]
@JoelBCarter this feature has been merged into master if you want to give building hyperv boxes a try.

**Comment by arizvisa** [comment]
It seems that a PR that adds support for hyperv-iso to the templates has already been merged which should resolve this?

I'm going to mark this issue as stale as it's been left open for almost 3 years now. Unless anybody has any objections, this issue will be closed in 1 month.

**Comment by arizvisa** [comment]
Resolved by PR #168.
